### ISSUE TITLE
Update Dependabot

### ISSUE THREAD

**Issue by phillip-wenig-frequenz** [frequenz-floss/frequenz-resampling-rs#7]
with the following options:

```yaml
    groups:
      compatible:
        update-types:
          - "minor"
          - "patch"
      artifacts:
        patterns:
          - "actions/*-artifact"
```
